{
 "title": "Arcus Platform",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Service Availability",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "count by (job) (up)", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Uptime by Service",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_attribute_uptime[5m])*.001",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Hubs Connected",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bridge_sessions_hub_total", "legendFormat": "hubs connected" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "abs(jvm_memory_heap_used)", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "DAO p99 times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "time" }
   ],
   "targets": [
    {
     "expr": "sum by(op)(dao_read_time{quantile=\"0.99\"})",
     "legendFormat": "{{op}} read time p99"
    },
    {
     "expr": "sum by(op)(dao_insert_time{quantile=\"0.99\"})",
     "legendFormat": "{{op}} insert time p99"
    },
    {
     "expr": "sum by(op)(dao_update_time{quantile=\"0.99\"})",
     "legendFormat": "{{op}} update time p99"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_count", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Authentication Failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(com_iris_bridge_metrics_bridge_metrics_bridge_client_authentication_failed[1m])"
    },
    {
     "expr": "com_iris_bridge_metrics_bridge_metrics_bridge_hub_authentication_failed"
    }
   ]
  },
  {
   "title": "Driver Service Jobs (per second)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(driver_service_pool_tasks_submitted[1m])",
     "legendFormat": "{{job}} tasks submitted"
    },
    {
     "expr": "rate(driver_service_pool_tasks_completed[1m])",
     "legendFormat": "{{job}}-completed-{{quantile}}"
    },
    {
     "expr": "rate(driver_service_pool_tasks_failed[1m])",
     "legendFormat": "{{job}}-failed-{{quantile}}"
    },
    {
     "expr": "driver_service_pool_enqueuetime",
     "legendFormat": "{{job}}-enueuetime-{{quantile}}"
    }
   ]
  },
  {
   "title": "Client Bridge rps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(com_iris_bridge_metrics_bridge_metrics_bridge_client_http_received[1m])",
     "legendFormat": "{{job}} http rpm"
    }
   ]
  },
  {
   "title": "Kafka Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(messages_platform_cache_recv_from_count[5m])",
     "legendFormat": "recv {{job}}"
    },
    {
     "expr": "rate(messages_platform_cache_sent_from_count[5m])",
     "legendFormat": "sent {{job}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bridge_ssl_connect_accepted[1m])"
    }
   ]
  },
  {
   "title": "Notifications Dispatched",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(notifications_dispatch_apns[1m])",
     "legendFormat": "apns dispatched"
    },
    {
     "expr": "rate(notifications_dispatch_email[1m])",
     "legendFormat": "emails dispatched"
    },
    {
     "expr": "rate(notifications_dispatch_ivr[1m])"
    }
   ]
  }
 ]
}