apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: default
spec:
  serviceName: kafka
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka
    spec:
      containers:
      - env:
        - name: ZOOKEEPER
          valueFrom:
            configMapKeyRef:
              key: ZOOKEEPER
              name: arcus-config
        - name: ZOOKEEPEROPS
          valueFrom:
            configMapKeyRef:
              key: ZOOKEEPEROPS
              name: arcus-config
        - name: KAFKA_HSIZE
          valueFrom:
            configMapKeyRef:
              key: KAFKA_HSIZE
              name: arcus-config
        - name: KAFKA_REPLICATION
          valueFrom:
            configMapKeyRef:
              key: KAFKAOPS_REPLICATION # shared for now
              name: arcus-config
        - name: KAFKAOPS_REPLICATION
          valueFrom:
            configMapKeyRef:
              key: KAFKAOPS_REPLICATION
              name: arcus-config
        - name: ADVERTISED_HSTN
          valueFrom:
            configMapKeyRef:
              key: ADVERTISED_HSTN
              name: arcus-config
        - name: LISTENERS
          value: PLAINTEXT://localhost:9092
        - name: KAFAOPS_METRICS_LOG_RETENTION_BYTES
          value: "1073741824"
        - name: KAFKA_LOG_SEGMENT_BYTES
          value: "10485760"
        - name: KAFAOPS_METRICS_LOG_RETENTION_MS
          value: "3600000"
        - name: KAFKA_LOG_RETENTION_BYTES
          value: "1073741824"
        - name: KAFKA_LOG_RETENTION_MS
          value: "3600000"
        ports:
        - containerPort: 9092
          name: tcp-9092
        image: us-west1-docker.pkg.dev/arcus-238802/arcus-prod/arcus/kafka:latest
        imagePullPolicy: Always
        name: kafka
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.1"
            memory: "512Mi"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: "/data"
          name: kafka-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 998
        runAsGroup: 998
        fsGroup: 998
      terminationGracePeriodSeconds: 30
  volumeClaimTemplates:
  - metadata:
      name: kafka-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi

